import 'dart:ui';

import 'app_styles.dart';

List<Color> folderColors = [
  kLightBlueColor,
  kLightYellowColor,
  kLightRedColor,
  kLightGreenColor,
  kLightBlueColor,
  kLightYellowColor,
  kLightRedColor,
  kLightGreenColor,
  kLightBlueColor,
  kLightYellowColor,
  kLightRedColor,
  kLightGreenColor,
  kLightBlueColor,
  kLightYellowColor,
  kLightRedColor,
  kLightGreenColor,
];

List<Color> textColors = [
  kBlueColor,
  kYellowColor,
  kRedColor,
  kGreenColor,
  kBlueColor,
  kYellowColor,
  kRedColor,
  kGreenColor,
  kBlueColor,
  kYellowColor,
  kRedColor,
  kGreenColor,
  kBlueColor,
  kYellowColor,
  kRedColor,
  kGreenColor,
];

List<String> folderColoredIcon = [
  'folder_icon_blue.svg',
  'folder_icon_yellow.svg',
  'folder_icon_red.svg',
  'folder_icon_green.svg',
  'folder_icon_blue.svg',
  'folder_icon_yellow.svg',
  'folder_icon_red.svg',
  'folder_icon_green.svg',
  'folder_icon_blue.svg',
  'folder_icon_yellow.svg',
  'folder_icon_red.svg',
  'folder_icon_green.svg',
  'folder_icon_blue.svg',
  'folder_icon_yellow.svg',
  'folder_icon_red.svg',
  'folder_icon_green.svg',
];

List<String> moreColoredIcon = [
  'more_vertical_icon_blue.svg',
  'more_vertical_icon_yellow.svg',
  'more_vertical_icon_red.svg',
  'more_vertical_icon_green.svg',
  'more_vertical_icon_blue.svg',
  'more_vertical_icon_yellow.svg',
  'more_vertical_icon_red.svg',
  'more_vertical_icon_green.svg',
  'more_vertical_icon_blue.svg',
  'more_vertical_icon_yellow.svg',
  'more_vertical_icon_red.svg',
  'more_vertical_icon_green.svg',
  'more_vertical_icon_blue.svg',
  'more_vertical_icon_yellow.svg',
  'more_vertical_icon_red.svg',
  'more_vertical_icon_green.svg',
];

List<String> folderNames = [
  'Mobile apps',
  'SVG icons',
  'Prototypes',
  'Avatars',
  'Mobile apps',
  'SVG icons',
  'Prototypes',
  'Avatars',
  'Mobile apps',
  'SVG icons',
  'Prototypes',
  'Avatars',
  'Mobile apps',
  'SVG icons',
  'Prototypes',
  'Avatars',
];

List<String> folderDates = [
  'December 20.2020',
  'December 14.2020',
  'December 20.2020',
  'December 14.2020',
  'December 20.2020',
  'December 14.2020',
  'December 20.2020',
  'December 14.2020',
  'December 20.2020',
  'December 14.2020',
  'December 20.2020',
  'December 14.2020',
  'December 20.2020',
  'December 14.2020',
  'December 20.2020',
  'December 14.2020',
];